Update .config/memo/plugins/commit Update .config/yay/extra-packeges Update 2_install-go.zsh

diff --git a/dot_config/private_memo/private_plugins/executable_commit b/dot_config/private_memo/private_plugins/executable_commit
--- a/dot_config/private_memo/private_plugins/executable_commit
+++ b/dot_config/private_memo/private_plugins/executable_commit
@@ -1,5 +1,22 @@
 #!/bin/zsh
 
+usage() {
+    echo "Commit Memo"
+    exit 0
+}
+
+for arg in "$@"; do
+  case $arg in
+    -usage)
+      usage
+      ;;
+    *)
+      echo "Invalid option: $arg" 1>&2
+      usage
+      ;;
+  esac
+done
+
 cd "$(ghq root)/github.com/oyoshot/_memo"
 
 git pull --no-edit
